# Generated by Django 3.0.3 on 2020-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time_in',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='workday',
            name='time_out',
            field=models.TimeField(default=None),
        ),
    ]
