# Generated by Django 3.0.3 on 2020-06-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheet.User'),
        ),
    ]
