# Generated by Django 3.0.3 on 2020-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_workday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time_out',
            field=models.TimeField(default=None, null=True),
        ),
    ]
