# Generated by Django 3.0.3 on 2020-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_auto_20200603_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='total_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
